name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t chetanmarol/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true chetanmarol/react-test npm test

      - run: docker build -t chetanmarol/multi-client ./client
      - run: docker build -t chetanmarol/multi-nginx ./nginx
      - run: docker build -t chetanmarol/multi-server ./server
      - run: docker build -t chetanmarol/multi-worker ./worker

      - run: docker push chetanmarol/multi-client
      - run: docker push chetanmarol/multi-nginx
      - run: docker push chetanmarol/multi-server
      - run: docker push chetanmarol/multi-worker
      
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
        
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          application_name: multi-docker
          environment_name: multi-docker-env
          aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          existing_bucket_name: elasticbeanstalk-eu-north-1-462719822395
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip